components/ChatBoxFrame.tsx
components/ChatBubble.tsx
components/Input.tsx
components/RateLimitForm.tsx
hooks/useChat.ts
hooks/useRateLimit.ts
pages/agents/[agentId]/index.tsx
types/models.ts

Feat(130): add rate limit to chat with agent

---

widgets/wordpress/chaindesk.php
widgets/wordpress/readme.txt

* blog
* feat: apply wp guidlines
---------

Feat: 131-wp-plugin-guidelines (#135)

---

widgets/wordpress/chatbotgpt.php
widgets/wordpress/readme.txt

fix: 🐛 wordpress plugin

---

apps/dashboard/components/AgentInputs/CommonInterfaceInput.tsx
apps/dashboard/components/AgentInputs/InitialBubbleMessageCheckbox.tsx
apps/dashboard/components/ChatBubble.tsx
packages/lib/types/models.ts

feat: 🎸 Disable init message on bubble

---

packages/emails/src/SignIn.tsx
packages/emails/src/index.ts
packages/lib/auth.ts
packages/lib/package.json
packages/lib/verification-sender.tsx
pnpm-lock.yaml

feat: 🎸 custom signin email

---

apps/dashboard/components/ChatBubble.tsx

[discord issue](https://discord.com/channels/1094372577587241000/1094373533049692280/threads/1161615063019438100)
icon size on the bubble is not well fit.

fix: 🐛 icon size on bubble

---

apps/dashboard/components/ChatBox.tsx
apps/dashboard/components/ChatSection.tsx
apps/dashboard/components/ConversationList.tsx
apps/dashboard/hooks/useChat.ts
apps/dashboard/pages/agents/[agentId]/index.tsx
apps/dashboard/pages/chat/index.tsx

fix: 🐛 lag and new chat lags

---

apps/dashboard/hooks/useChat.ts
apps/dashboard/pages/agents/[agentId]/index.tsx
apps/dashboard/pages/chat/index.tsx

revalidation should not be on chatbubble

fix: 🐛 chat lags

---

apps/dashboard/components/ChatBox.tsx
apps/dashboard/components/ChatBoxFrame.tsx
apps/dashboard/components/ChatBubble.tsx
apps/dashboard/components/ResolveButton.tsx
apps/dashboard/hooks/useChat.ts
apps/dashboard/pages/agents/[agentId]/index.tsx
apps/dashboard/pages/api/conversations/[conversationId].ts
apps/dashboard/pages/chat/index.tsx
packages/lib/types/dtos.ts
packages/prisma/migrations/20231016135613_/migration.sql
packages/prisma/schema.prisma

feat: 🎸 Resolve conversation

---

apps/dashboard/components/CreateDatastoreModal.tsx

UI improvement on DatastoreModal

fix: 🐛 add scroll to modal

---

apps/dashboard/components/TopProgressBar.tsx
apps/dashboard/hooks/useNprogress.ts

fix: 🐛 loading issues

---

apps/dashboard/pages/api/agents/[id]/query.tsx
packages/lib/chatv2.ts
packages/lib/truncateChatMessages.ts

fix: 🐛 max token limit checker

---

apps/dashboard/components/IFrameWidgetSettings.tsx
apps/dashboard/components/Layout/Navigation.tsx
apps/dashboard/components/Layout/index.tsx
apps/dashboard/components/cs-landing-page/Header.jsx
apps/dashboard/components/cs-landing-page/Hero.tsx
apps/dashboard/components/landing-page/Cta.tsx
apps/dashboard/components/landing-page/Header.jsx
apps/dashboard/components/landing-page/Hero.backup.jsx
apps/dashboard/components/landing-page/Hero.jsx
apps/dashboard/components/landing-page/HeroChatGPTPlugin.jsx
apps/dashboard/components/landing-page/PricingSection.tsx
apps/dashboard/pages/api/openai/plugin/openapi-yaml.ts
apps/dashboard/pages/integrations/crisp/config.tsx
apps/dashboard/pages/products/[slug].tsx
apps/dashboard/pages/signin.tsx
packages/lib/config.ts

Removed all of the hard-coded dashboard and api urls and replaced it with an exported variable in config file

removed hard-coded app urls

---

apps/dashboard/components/AnalyticsCard.tsx
apps/dashboard/components/charts/AreaChart.tsx
apps/dashboard/components/charts/GeoChart.tsx
apps/dashboard/pages/analytics/index.tsx
apps/dashboard/pages/api/analytics/index.ts

fix: 🐛 scale issue on bars

---

packages/lib/agent/tools/form.ts
packages/lib/agent/tools/http.ts
packages/lib/agent/tools/type.ts
packages/lib/chatv3.ts

fix: 🐛 empower http tool

---

apps/dashboard/components/DatasourceForms/WebSiteForm.tsx
apps/dashboard/components/Input.tsx
packages/lib/isUrlBlocked.ts
packages/lib/loaders/google-drive-folder.ts
packages/lib/loaders/notion.ts
packages/lib/loaders/web-site.ts
packages/lib/types/models.ts
packages/ui/src/Input.tsx

feat: 🎸 blacklist urls from website loader

---

apps/dashboard/components/DarftReplyInput.tsx

fix: 🐛 faulty grammar reply on correct input

---

apps/dashboard/components/AgentSettingsTab/AgentGeneralSettingsTab.tsx
apps/dashboard/pages/integrations/crisp/config.tsx
packages/integrations/crisp/api/webhook.ts
packages/lib/api-error.ts
packages/lib/createa-api-handler.ts

fix: 🐛 crisp issues

---

apps/dashboard/pages/api/conversations/[conversationId]/index.tsx
apps/dashboard/pages/api/conversations/[conversationId]/message.tsx
apps/dashboard/pages/api/logs/index.ts
apps/dashboard/pages/logs/index.tsx
packages/integrations/crisp/api/webhook.ts

fix: 🐛 crisp human out of sync

---

packages/integrations/crisp/api/webhook.ts

fix: 🐛 crisp operator message

---

packages/ui/src/Chatbox/AnimateMessagesOneByOne.tsx
packages/ui/src/Chatbox/ChatMessage.tsx
packages/ui/src/Chatbox/index.tsx
packages/ui/src/embeds/chat-base.tsx

todo: animate on new create chat.

fix: remove flickering

---

apps/dashboard/components/AgentInputs/HttpToolInput.tsx

Excluding headers from url tracking.

fix tracking header values
